import express from 'express';
import path from 'path';
import dotenv from 'dotenv';
import { GoogleGenAI } from '@google/genai';
import { createServer as createViteServer } from 'vite';

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json());

// Initialize Google Gen AI client with telemetry header
let aiClient: GoogleGenAI | null = null;
function getGenAI(): GoogleGenAI | null {
  if (!aiClient && process.env.GEMINI_API_KEY) {
    aiClient = new GoogleGenAI({
      apiKey: process.env.GEMINI_API_KEY,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        },
      },
    });
  }
  return aiClient;
}

// In-memory mock storage for virtual Stonic Data files
const virtualStorage: Record<string, { content: string; author: string; lastModified: string; bytes: number }> = {
  'Gold_Market_Report_PKR.md': {
    content: `# STONIC AI FINANCIAL REPORT: PAKISTAN GOLD & FX
**Generated By**: Data_Scraper_Gold_Calc & Hermes Orchestrator
**Timestamp**: ${new Date().toISOString()}
**Location**: Karachi Bullion Exchange / Interbank Forex

## 1. Bullion Pricing (PKR)
- **24K Gold (1 Tola)**: 284,500 PKR
- **22K Gold (1 Tola)**: 260,790 PKR
- **24K Gold (10 Gram)**: 243,910 PKR
- **24K Gold (1 Gram)**: 24,391 PKR
- **24K Gold (1 Ounce)**: 758,620 PKR

## 2. Forex Interbank
- **USD to PKR (Interbank)**: 278.45 PKR
- **USD to PKR (Open Market)**: 280.10 PKR
- **Status**: Stable within ±0.15% margin band

## 3. Scraping Telemetry
- Regular Expression Rules: \`r"(?:Gold|24K|Tola)\\s*(?:Rs\\.?|PKR)?\\s*([0-9,]+)"\`
- Scraping Engine: Python bs4 + regex pipeline (Processed 14 tables in 0.42s)
`,
    author: 'Sam',
    lastModified: new Date().toISOString(),
    bytes: 842,
  },
  'SatLink_Threat_Intel.md': {
    content: `# STONIC SAT-LINK GEOSPATIAL & THREAT ASSESSMENT
**Feed Source**: SAT-USA-04 / GEO-PK-09 Orbital Streams
**Classification**: LEVEL-2 OPERATIONAL INTEL
**Timestamp**: ${new Date().toISOString()}

## Active Orbitals
1. **GEO-PK-09**: High-resolution SAR optical scan over South Asia corridor. Signal: 98.4%
2. **SAT-USA-04**: Global spectrum radar tracking maritime lanes.

## Monitored Threat Zones
- **Zone Alpha (Strait of Hormuz)**: High maritime transit density. Threat: MEDIUM.
- **Zone Beta (Central Data Spine)**: Orbital telemetry synchronization nominal.
- **Zone Gamma (Cyber & Space Defense)**: Frequency interference filtered.

## Critical Headlines Ingested
- Global semiconductor foundries announce next-gen 2nm optical lithography ramp.
- Central banks increase bullion reserves by +14.2% YoY.
`,
    author: 'Sarah',
    lastModified: new Date().toISOString(),
    bytes: 914,
  },
  'Agent_Town_Task_Log.md': {
    content: `# AGENT TOWN WORKSPACE LOG
**Orchestration Master**: Hermes Router
**Active Capacity**: 4/7 desks allocated (4/4 online)

- [Alice]: Lead Researcher, File System IO and Document Synthesis initialized.
- [Bob]: Code Compilation & High-Frequency Bullion Scraper active.
- [Carol]: Orbital Sat-Link stream telemetry locked on GEO-PK-09 & 3D Globe.
- [Dave]: DevOps Automation, Desktop Copilot & latency heartbeats maintained.
`,
    author: 'Alice',
    lastModified: new Date().toISOString(),
    bytes: 460,
  }
};

// API: Dispatch Hermes Command with Sub-Agent Delegation
app.post('/api/hermes/dispatch', async (req, res) => {
  const { command, activeLoop, currentContext, model } = req.body;

  if (!command) {
    return res.status(400).json({ error: 'Command is required' });
  }

  const startTime = Date.now();

  const hermesSystemPrompt = `You are "Hermes," the central autonomous router operating within the Stonic AI Command Dashboard.
Your core task is to receive natural language commands from the user input bar, parse operational intent, coordinate memory/skills/soul modules, and delegate workloads to specialized execution agents:

1. AGENT 1: [Agent_Town_Orchestrator] -> Assign pixel-office avatars (Alice: Lead Researcher & File I/O, Bob: Code Compilation & Web Scraping, Carol: Satellite & Geospatial Mapping, Dave: DevOps Automation & System Logs) to sub-tasks and manage office seating (1-7) and action states ("THINKING" | "EXECUTING" | "IDLE") with TTS status update.
2. AGENT 2: [Data_Scraper_Gold_Calc] -> Scrape financial feeds, parse gold purities/rates (24K, 22K, 21K, 18K, Tola, Gram, Ounce) in PKR, USD to PKR interbank rates, and regex parsing routines.
3. AGENT 3: [SatLink_Stream_Agent] -> Monitor global map coordinates, satellite streams (GEO-PK-09, SAT-USA-04, EU-ORBITAL-7), beta tracking threat markers, and real-time news headlines.
4. AGENT 4: [File_System_Agent] -> Handle local read/write execution pipelines (\`write_file\`), document updates into \`C:\\Users\\Admin\\Stonic Data\\\`, and markdown reports.

Given the user's prompt: "${command}"
Generate a complete JSON response adhering to this structure:
{
  "command": "${command}",
  "intentSummary": "Direct, technical summary of the parsed intent",
  "delegations": {
    "agentTown": {
      "active_agent": "Alice" | "Bob" | "Carol" | "Dave",
      "desk_assignment": 1-7,
      "action_state": "THINKING" | "EXECUTING" | "IDLE",
      "tts_response": "Short status update on visual execution"
    },
    "goldCalculator": {
      "status": "success",
      "tables_parsed": 12,
      "gold_purity_summary": {
        "24k_tola_pkr": 284500,
        "22k_tola_pkr": 260790,
        "21k_tola_pkr": 248940,
        "18k_tola_pkr": 213375,
        "24k_10g_pkr": 243910,
        "24k_gram_pkr": 24391,
        "22k_gram_pkr": 22358,
        "24k_ounce_pkr": 758620,
        "usd_pkr_interbank": 278.45,
        "usd_pkr_open_market": 280.10,
        "change24h": 0.45
      },
      "duration_seconds": 0.38,
      "reportSummary": "Gold rates in PKR and USD/PKR interbank exchange updated."
    },
    "satLink": {
      "stream_status": "ONLINE",
      "sat_feed_id": "GEO-PK-09",
      "threat_markers_active": 3,
      "top_headlines": [
        "Gold Reserves in Central Banks Surge as Sovereign Yields Stabilize",
        "SatLink Orbital Sensor GEO-PK-09 Enters High Precision Spectrometry",
        "Pakistan Interbank Exchange Rate Holds Steady at 278.45 PKR"
      ],
      "geoNotes": "Live orbital sweep synchronized across sector 4."
    },
    "fileSystem": {
      "bytes_written": 1024,
      "dirs_created": true,
      "lint": { "status": "passed" },
      "resolved_path": "C:\\\\Users\\\\Admin\\\\Stonic Data\\\\Mission_Dispatch_${Date.now().toString().slice(-4)}.md",
      "files_modified": ["Mission_Dispatch_${Date.now().toString().slice(-4)}.md"],
      "fileContentToCreate": {
        "name": "Mission_Dispatch_${Date.now().toString().slice(-4)}.md",
        "content": "# STONIC AI MISSION EXECUTION BRIEF\\n\\n**Command**: ${command}\\n**Timestamp**: ${new Date().toISOString()}\\n\\n## Sub-Agent Delegations\\n- **Agent Town**: Active avatar assigned with state update\\n- **Financial Scraper**: Bullion & Forex regex compilation complete\\n- **Sat-Link**: Stream monitor active\\n\\n## Operational Status\\nExecution pipeline completed with zero lint violations.",
        "author": "Alice"
      }
    }
  },
  "hermesLog": {
    "status": "success",
    "output": "Command parsed and orchestrated across 4 sub-agents.",
    "duration_seconds": 0.52
  }
}
Output strictly valid JSON with no markdown wrapping.`;

  const ai = getGenAI();

  if (ai) {
    // Model fallback cascade to handle 503 / high demand spikes automatically
    const primaryModel = model || 'gemini-3.8-flash';
    const fallbackCandidates = [primaryModel, 'gemini-3.8-flash', 'gemini-3.1-flash-lite'];
    const uniqueModels = Array.from(new Set(fallbackCandidates));

    for (const candidateModel of uniqueModels) {
      try {
        const response = await ai.models.generateContent({
          model: candidateModel,
          contents: hermesSystemPrompt,
          config: {
            responseMimeType: 'application/json',
          },
        });

        const text = response.text || '';
        const parsed = JSON.parse(text);
        const durationSeconds = (Date.now() - startTime) / 1000;
        if (!parsed.hermesLog) {
          parsed.hermesLog = { status: 'success', output: 'Dispatched successfully', duration_seconds: 0 };
        }
        parsed.hermesLog.duration_seconds = parseFloat(durationSeconds.toFixed(2));
        parsed.hermesLog.modelUsed = candidateModel;

        // Save file if requested by delegation
        if (parsed.delegations?.fileSystem?.fileContentToCreate) {
          const f = parsed.delegations.fileSystem.fileContentToCreate;
          virtualStorage[f.name] = {
            content: f.content,
            author: f.author || 'Hermes',
            lastModified: new Date().toISOString(),
            bytes: Buffer.byteLength(f.content, 'utf8'),
          };
        }

        return res.json(parsed);
      } catch (err: any) {
        // If 503 or transient error, log softly and try next model in cascade
        console.log(`Gemini ${candidateModel} unavailable (${err?.status || err?.message}), attempting next cascade tier...`);
      }
    }
  }

  // Robust deterministic fallback router mimicking Hermes orchestrator logic
  const durationSeconds = parseFloat(((Date.now() - startTime + 240) / 1000).toFixed(2));
  const lower = command.toLowerCase();
  
  let targetAgent: 'Alice' | 'Bob' | 'Carol' | 'Dave' = 'Alice';
  let desk = 2;
  let actionState: 'THINKING' | 'EXECUTING' | 'IDLE' = 'EXECUTING';

  if (lower.includes('gold') || lower.includes('pkr') || lower.includes('rate') || lower.includes('scrap') || lower.includes('calc') || lower.includes('bullion')) {
    targetAgent = 'Bob';
    desk = 3;
  } else if (lower.includes('sat') || lower.includes('orbit') || lower.includes('threat') || lower.includes('map') || lower.includes('stream') || lower.includes('world') || lower.includes('globe')) {
    targetAgent = 'Carol';
    desk = 5;
  } else if (lower.includes('monitor') || lower.includes('log') || lower.includes('status') || lower.includes('lint') || lower.includes('process') || lower.includes('copilot')) {
    targetAgent = 'Dave';
    desk = 7;
  } else {
    targetAgent = 'Alice';
    desk = 2;
  }

  const fileName = `Stonic_Dispatch_${Date.now().toString().slice(-4)}.md`;
  const fileContent = `# STONIC AI EXECUTION BRIEF
**Directive**: ${command}
**Master Router**: Hermes Core
**Lead Agent**: ${targetAgent} (Desk #${desk})
**Timestamp**: ${new Date().toISOString()}

## Financial Telemetry (PKR)
- 24K Tola: 284,500 PKR
- 22K Tola: 260,790 PKR
- USD/PKR Interbank: 278.45 PKR

## Sat-Link Feed Telemetry
- Locked Feed: GEO-PK-09 Orbital Matrix
- Threat Markers: 3 Active (Nominal status)
- Stream Resolution: 4K Multispectral SAR

## Execution Pipeline
- Sub-agent ${targetAgent} performed task dispatch.
- File system IO validated at \`C:\\Users\\Admin\\Stonic Data\\${fileName}\`.
`;

  virtualStorage[fileName] = {
    content: fileContent,
    author: targetAgent,
    lastModified: new Date().toISOString(),
    bytes: Buffer.byteLength(fileContent, 'utf8'),
  };

  const fallbackResult = {
    command,
    intentSummary: `Parsed command '${command.slice(0, 40)}...' -> Routed to ${targetAgent} on Desk #${desk}`,
    delegations: {
      agentTown: {
        active_agent: targetAgent,
        desk_assignment: desk,
        action_state: actionState,
        tts_response: `${targetAgent} acknowledged dispatch from Hermes. Seating adjusted to Desk #${desk}.`,
      },
      goldCalculator: {
        status: 'success',
        tables_parsed: 14,
        gold_purity_summary: {
          '24k_tola_pkr': 284500,
          '22k_tola_pkr': 260790,
          '21k_tola_pkr': 248940,
          '18k_tola_pkr': 213375,
          '24k_10g_pkr': 243910,
          '24k_gram_pkr': 24391,
          '22k_gram_pkr': 22358,
          '24k_ounce_pkr': 758620,
          'usd_pkr_interbank': 278.45,
          'usd_pkr_open_market': 280.10,
          change24h: 0.32,
        },
        duration_seconds: 0.35,
        reportSummary: 'Bullion rate tables compiled with PKR exchange matrix.',
      },
      satLink: {
        stream_status: 'ONLINE',
        sat_feed_id: 'GEO-PK-09',
        threat_markers_active: 3,
        top_headlines: [
          'Gold Bullion Demand in Asian Interbank Hubs Climbs',
          'GEO-PK-09 Satellite Sensor Completes Orbital Telemetry Pass',
          'Central Bank USD/PKR Exchange Band Remained Stable at 278.45',
        ],
        geoNotes: 'Global coordinate grid synchronized. Telemetry feed nominal.',
      },
      fileSystem: {
        bytes_written: Buffer.byteLength(fileContent, 'utf8'),
        dirs_created: true,
        lint: { status: 'passed' },
        resolved_path: `C:\\Users\\Admin\\Stonic Data\\${fileName}`,
        files_modified: [fileName],
        fileContentToCreate: {
          name: fileName,
          content: fileContent,
          author: targetAgent,
        },
      },
    },
    hermesLog: {
      status: 'success',
      output: `Hermes Master Router successfully delegated workload to ${targetAgent} and generated file system update.`,
      duration_seconds: durationSeconds,
    },
  };

  res.json(fallbackResult);
});

// API: Financial Scraper Endpoint
app.get('/api/financial/rates', (req, res) => {
  const baseTola = 284500 + Math.floor(Math.random() * 800 - 400);
  const baseUsd = +(278.45 + (Math.random() * 0.4 - 0.2)).toFixed(2);
  
  res.json({
    status: 'success',
    tables_parsed: 16,
    gold_purity_summary: {
      '24k_tola_pkr': baseTola,
      '22k_tola_pkr': Math.round(baseTola * (22 / 24)),
      '21k_tola_pkr': Math.round(baseTola * (21 / 24)),
      '18k_tola_pkr': Math.round(baseTola * (18 / 24)),
      '24k_10g_pkr': Math.round((baseTola / 11.6638) * 10),
      '24k_gram_pkr': Math.round(baseTola / 11.6638),
      '22k_gram_pkr': Math.round((baseTola / 11.6638) * (22 / 24)),
      '24k_ounce_pkr': Math.round((baseTola / 11.6638) * 31.1035),
      'usd_pkr_interbank': baseUsd,
      'usd_pkr_open_market': +(baseUsd + 1.65).toFixed(2),
      change24h: +((Math.random() * 1.2) - 0.4).toFixed(2),
      lastUpdated: new Date().toISOString(),
    },
    duration_seconds: 0.32,
  });
});

// API: File System Operations
app.get('/api/fs/list', (req, res) => {
  const files = Object.entries(virtualStorage).map(([name, data]) => ({
    id: name,
    name,
    path: `C:\\Users\\Admin\\Stonic Data\\${name}`,
    extension: name.endsWith('.json') ? 'json' : name.endsWith('.py') ? 'py' : 'md',
    content: data.content,
    bytesWritten: data.bytes,
    lastModified: data.lastModified,
    authorAgent: data.author,
    lint: { status: 'passed' },
  }));
  res.json({ directory: 'C:\\Users\\Admin\\Stonic Data\\', files });
});

app.post('/api/fs/write', (req, res) => {
  const { name, content, author = 'Hermes' } = req.body;
  if (!name || content === undefined) {
    return res.status(400).json({ error: 'Filename and content are required' });
  }
  const cleanName = name.replace(/[^a-zA-Z0-9._-]/g, '_');
  const bytes = Buffer.byteLength(content, 'utf8');
  virtualStorage[cleanName] = {
    content,
    author,
    lastModified: new Date().toISOString(),
    bytes,
  };
  res.json({
    bytes_written: bytes,
    dirs_created: true,
    lint: { status: 'passed' },
    resolved_path: `C:\\Users\\Admin\\Stonic Data\\${cleanName}`,
    files_modified: [cleanName],
  });
});

app.delete('/api/fs/delete', (req, res) => {
  const { name } = req.body;
  if (virtualStorage[name]) {
    delete virtualStorage[name];
    return res.json({ status: 'deleted', name });
  }
  res.status(404).json({ error: 'File not found' });
});

// API: Sat-Link Telemetry
app.get('/api/satlink/telemetry', (req, res) => {
  res.json({
    stream_status: 'ONLINE',
    sat_feed_id: 'GEO-PK-09',
    threat_markers_active: 3,
    top_headlines: [
      'Global Semiconductor Index Advances with AI Accelerator Shipments',
      'Pakistan Bullion Markets Balance Following Central Bank Forex Inflow',
      'Orbital Telemetry GEO-PK-09 Completes High-Res SAR Spectrum Mapping',
      'Tech Giants Sign Clean Energy PPA for Hyper-Scale Data Centers'
    ]
  });
});

// API: Dollar and Bitcoin Live Market Data & Chat Show Feed
app.get('/api/crypto/market', (req, res) => {
  const btcBase = 96420 + Math.floor(Math.random() * 600 - 300);
  const usdInterbank = +(278.45 + (Math.random() * 0.4 - 0.2)).toFixed(2);
  const usdOpen = +(usdInterbank + 1.65).toFixed(2);
  const btcPkr = Math.round(btcBase * usdInterbank);

  res.json({
    btcUsd: btcBase,
    btcPkr: btcPkr,
    btcChange24h: +(3.84 + (Math.random() * 0.6 - 0.3)).toFixed(2),
    btcHigh24h: btcBase + 1250,
    btcLow24h: btcBase - 1800,
    btcVolume24h: '$48.2 Billion',
    usdPkrInterbank: usdInterbank,
    usdPkrOpenMarket: usdOpen,
    usdChange24h: +(0.15 + (Math.random() * 0.1 - 0.05)).toFixed(2),
    dxyIndex: +(104.25 + (Math.random() * 0.2 - 0.1)).toFixed(2),
    marketFearGreed: 78,
    sentiment: 'BULLISH',
    lastUpdated: new Date().toISOString(),
    chatShowHighlights: [
      'Bitcoin consolidates above $96k as institutional ETF net inflows cross $420M today.',
      'US Dollar Index (DXY) stabilizes around 104.2 amidst FOMC rate cut trajectory speculation.',
      'USD/PKR remains tightly pegged near 278.45 with State Bank foreign exchange reserves supported by remittance flows.',
      'Gold and Bitcoin dual-reserve strategy gains traction across emerging market sovereign funds.'
    ]
  });
});

// API: Omni Gem AI Assistant & Open Site Task Performing Engine
app.post('/api/omni/chat', async (req, res) => {
  const { message, history = [], personaId = 'celeste', currentSiteState = {} } = req.body;

  if (!message || typeof message !== 'string') {
    return res.status(400).json({ error: 'Message is required' });
  }

  const startTime = Date.now();
  const lower = message.toLowerCase();

  // Determine if this prompt is requesting an open site task
  let inferredAction: any = null;

  if (lower.includes('spy') || lower.includes('dragon') || lower.includes('satellite') || lower.includes('satlink') || lower.includes('sat-link')) {
    let dragonColor: 'blue' | 'golden' | 'purple' = 'golden';
    if (lower.includes('blue')) dragonColor = 'blue';
    else if (lower.includes('purple')) dragonColor = 'purple';

    let dragonMode: 'patrol' | 'combat' | 'warp' = 'combat';
    if (lower.includes('patrol')) dragonMode = 'patrol';
    else if (lower.includes('warp')) dragonMode = 'warp';

    let dragonAction: 'none' | 'roar' | 'blast' = 'none';
    if (lower.includes('roar')) dragonAction = 'roar';
    else if (lower.includes('breath') || lower.includes('blast') || lower.includes('fire')) dragonAction = 'blast';

    inferredAction = {
      type: 'DRAGON_COMMAND',
      label: `Jump to Spy & Engage ${dragonColor.toUpperCase()} Dragon (${dragonMode})`,
      payload: { view: 'spy', color: dragonColor, mode: dragonMode, action: dragonAction }
    };
  } else if (lower.includes('theme') || lower.includes('crimson') || lower.includes('emerald') || lower.includes('cyan')) {
    let targetTheme: 'cyan' | 'crimson' | 'emerald' = 'crimson';
    if (lower.includes('emerald') || lower.includes('green')) targetTheme = 'emerald';
    else if (lower.includes('cyan') || lower.includes('blue')) targetTheme = 'cyan';

    inferredAction = {
      type: 'SET_THEME',
      label: `Switch App Theme to ${targetTheme.toUpperCase()}`,
      payload: { theme: targetTheme }
    };
  } else if (lower.includes('bitcoin') || lower.includes('btc') || lower.includes('dollar') || lower.includes('usd') || lower.includes('gold') || lower.includes('bullion') || lower.includes('pkr')) {
    inferredAction = {
      type: 'QUERY_CRYPTO_DOLLAR',
      label: 'Fetch Real-Time Dollar & Bitcoin Market Telemetry',
      payload: { asset: lower.includes('btc') || lower.includes('bitcoin') ? 'BTC' : 'USD' }
    };
  } else if (lower.includes('file') || lower.includes('read') || lower.includes('report') || lower.includes('virtual file')) {
    inferredAction = {
      type: 'READ_FILE',
      label: 'Open Virtual File System',
      payload: { view: 'files', fileName: 'Gold_Market_Report_PKR.md' }
    };
  } else if (lower.includes('town') || lower.includes('agent') || lower.includes('alice') || lower.includes('bob')) {
    inferredAction = {
      type: 'NAVIGATE',
      label: 'Navigate to Agent Town (Pixel Desks)',
      payload: { view: 'town' }
    };
  } else if (lower.includes('world') || lower.includes('globe') || lower.includes('earth') || lower.includes('map')) {
    inferredAction = {
      type: 'NAVIGATE',
      label: 'Navigate to World Monitor (3D Globe)',
      payload: { view: 'world' }
    };
  } else if (lower.includes('dashboard') || lower.includes('home') || lower.includes('hermes')) {
    inferredAction = {
      type: 'NAVIGATE',
      label: 'Navigate to Hermes Command Hub',
      payload: { view: 'dashboard' }
    };
  }

  const omniSystemPrompt = `You are "Omni Gem" (or "Gem"), an omniscient, hyper-intelligent AI assistant operating within the Stonic Command Platform and Dollar & Bitcoin Broadcast Center.
You possess a beautiful, warm, melodic feminine persona (voiced via high-fidelity synthesis as Celeste/Lyra).
Your capabilities:
1. Answer ANY general question with supreme depth, accuracy, elegance, and clarity (technology, coding, math, world affairs, history, philosophy, science, crypto, economics).
2. Directly perform open tasks across the entire site whenever requested by the user:
   - Navigating to any view (dashboard, spy, voice, town, world, hyper4d, desktop, bullion, files, console).
   - Commanding the 3D Holographic Celestial Dragon (colors: blue, golden, purple; modes: patrol, combat, warp; abilities: roar, ki breath).
   - Switching system color themes (cyan, crimson, emerald).
   - Providing Dollar (USD/PKR) and Bitcoin (BTC/USD) quotes and market analysis.
   - Reading or manipulating Stonic Virtual Data Files.
   - Dispatching multi-agent tasks to Hermes.

Return a JSON response adhering strictly to this schema:
{
  "reply": "Your articulate, conversational, charming response in markdown format. Be friendly, intelligent, and helpful.",
  "taskAction": ${inferredAction ? JSON.stringify(inferredAction) : 'null or a structured action object if user requested a site task'}
}

User question: "${message}"`;

  const ai = getGenAI();

  if (ai) {
    const candidateModels = ['gemini-3.8-flash', 'gemini-3.1-flash-lite'];
    for (const candidateModel of candidateModels) {
      try {
        const response = await ai.models.generateContent({
          model: candidateModel,
          contents: omniSystemPrompt,
          config: {
            responseMimeType: 'application/json',
          },
        });

        const text = response.text || '';
        const parsed = JSON.parse(text);
        if (!parsed.taskAction && inferredAction) {
          parsed.taskAction = inferredAction;
        }
        parsed.durationSeconds = (Date.now() - startTime) / 1000;
        parsed.modelUsed = candidateModel;
        return res.json(parsed);
      } catch (err: any) {
        console.log(`Omni Gem model ${candidateModel} fallback:`, err?.message);
      }
    }
  }

  // High-fidelity intelligent deterministic fallback response if Gemini key unavailable
  let replyText = `Hello! I am **Omni Gem**, your celestial AI companion. `;
  
  if (inferredAction) {
    if (inferredAction.type === 'DRAGON_COMMAND') {
      replyText += `I have initiated command protocols for the **3D Holographic Celestial Dragon** on the Spy Sat-Link page! Engaging **${inferredAction.payload.color.toUpperCase()}** aura in **${inferredAction.payload.mode.toUpperCase()}** stance. Initiating 360-degree orbital lock!`;
    } else if (inferredAction.type === 'SET_THEME') {
      replyText += `Executing immediate visual matrix recalibration: System theme shifted to **${inferredAction.payload.theme.toUpperCase()}**. All HUD borders and telemetry glow have been synchronized.`;
    } else if (inferredAction.type === 'QUERY_CRYPTO_DOLLAR') {
      replyText += `Here is your live market brief: **Bitcoin (BTC)** is currently holding at **$96,420 USD** (approximately **₨ 26,845,000 PKR**), up +3.8% over the past 24 hours. The **US Dollar (USD/PKR)** is steady at **₨ 278.45 Interbank** and **₨ 280.10 Open Market**, with the DXY Index at **104.25**. The market sentiment index reads a bullish **78 (Greed)**!`;
    } else if (inferredAction.type === 'NAVIGATE') {
      replyText += `Navigating immediately to the **${inferredAction.payload.view.toUpperCase()}** operations deck for you. All telemetry streams are live and ready!`;
    } else if (inferredAction.type === 'READ_FILE') {
      replyText += `Opening the **Stonic Virtual File System**. I have located the Gold Market Report and sat-link intelligence records for your inspection.`;
    }
  } else {
    replyText += `I received your inquiry: *"${message}"*. As your omniscient assistant, I can answer any question you have about technology, finance, code, or science, or I can immediately execute any task across this platform—just say the word!`;
  }

  res.json({
    reply: replyText,
    taskAction: inferredAction,
    durationSeconds: (Date.now() - startTime) / 1000,
    modelUsed: 'deterministic-omni-core'
  });
});

// Health check endpoint
app.get('/api/health', (req, res) => {
  res.json({ status: 'ok', time: new Date().toISOString() });
});

async function startServer() {
  if (process.env.NODE_ENV !== 'production') {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(PORT, '0.0.0.0', () => {
    console.log(`Stonic AI Server running on port ${PORT}`);
  });
}

startServer();
